### ISSUE TITLE
Integrate Upsolver Expectations with dbt model contracts and constraints

### ISSUE THREAD

**Issue by rhasson** [Upsolver/dbt-upsolver#20]
Upsolver introduced support for adding data quality expectations when creating or altering a COPY FROM (ingestion) job.

The Upsolver syntax is as follows:

```
CREATE JOB <job_name> ...   
                        WITH EXPECTATION <expectation_name> {CHECK | EXPECT} <sql_predicate> ON VIOLATION {DROP | WARN} 
					    [WITH EXPECTATION ...]

ALTER JOB <job_name> ADD EXPECTATION <expectation_name> {CHECK | EXPECT} <sql_predicate> ON VIOLATION {DROP | WARN} 

ALTER JOB <job_name> DROP EXPECTATION <expectation_name>
```

dbt v.1.5 introduced [model contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts) which allows you to configure [model constraints](https://docs.getdbt.com/reference/resource-properties/constraints).

I propose allowing users to configure data quality expectations using model constraints. 

Take this COPY FROM model as example - `ingest_to_datalake.sql`:

```
{{ config(
         materialized='incremental',
         sync=True,
         source = 'S3',
          options={
           'CONTENT_TYPE': 'JSON',
           'LOCATION': 's3://upsolver-samples/orders/',
           'COMPUTE_CLUSTER': 'SQLake'
         },
          partition_by=[{'field':'event_date', 'type': 'date'}],
          primary_key=[{'field':'order_id', 'type': 'string'}]
        )
}}
SELECT * FROM {{ source('samples', 'upsolver_s3_samples') }}
```

The model contract/constraints in the YAML file - `schema.yml` - will be:

```
models:
  - name: ingest_to_datalake
    
    # required
    config:
      contract:
        enforced: true
    
    # model-level constraints
    constraints:
      - type: primary_key
        columns: ['order_id']
      - type: check
        columns: [order_date, event_date]
        expression: "order_date <= event_date"
        name: valid_order_date_from_event_date
      - type: ...
    
    columns:
      - name: order_id
        data_type: string
        
        # column-level constraints
        constraints:
          - type: not_null
          - type: check
            expression: "REGEXP_LIKE(order_id, '^[0-9]{4}[a-z]{5}$')"
            name: order_id_match_pattern

      - name: event_date
      - name: order_date
      - name: ...
```
When this model and YAML files are compiled they result in two actions.
First is a DDL to create the data lake table:

```
CREATE TABLE "default_glue_catalog"."database_xxxx"."ingest_to_datalake" (
  order_id string,
  event_date date,
  order_date date,
)
PARTITIONED BY (event_date)
PRIMARY KEY (order_id);

```
Second is the SQL to create the ingestion job:

```
CREATE SYNC JOB ingest_to_datalake_job
  'COMPUTE_CLUSTER': 'SQLake'
  'CONTENT_TYPE': 'JSON'
AS COPY FROM S3 upsolver_s3_samples
  'LOCATION': 's3://upsolver-samples/orders/'
INTO "default_glue_catalog"."database_xxxx"."ingest_to_datalake"
WITH EXPECTATION valid_order_date_from_event_date EXPECT order_date <= event_date ON VIOLATION WARN
WITH EXPECTATION order_id_match_pattern EXPECT REGEXP_LIKE(order_id, '^[0-9]{4}[a-z]{5}$') ON VIOLATION WARN
WITH EXPECTATION not_null__order_id EXPECT order_id IS NOT NULL ON VIOLATION WARN;
```
**Note:**
1. Model-level and column-level constraints compile to the same `WITH/ADD EXPECTATION` in Upsolver, there is no distinction between them.
2. All expectations are set to WARN.  Even though Upsolver supports DROP, it is not supported right now.
3. The following dbt constraint types are NOT supported: primary_key, unique, foreign_key
4. Constraint of type `not_null` compiles to `EXPECT <column_name> IS NOT NULL ...` in `CREATE JOB`
5. If constraint of type `not_null` doesn't include a `name` property, automatically create one using the format `not_null__` (two underscores) and the column name. For example: `not_null__order_id`
6. When updating a model contract/constraint, use the `ALTER JOB ... ADD EXPECTATION` syntax. Note that currently you can only add a single expectation per ALTER JOB statement. If you need to add multiple expectations, the ALTER statement needs to be executed once per expectation.

For target tables other than data lake, like Snowflake, we don't generate the DDL to create a target table, that is automatically done by Upsolver.  For those use cases, the model constraints are compiled to `WITH EXPECTATION` statements to be included with the `CREATE JOB` statement.  Only `not_null` and `check` types will be supported. Other constraint types are to be ignored.
